Part 2: Patch adb code to work with Android 15 QPR1 with legacy Function FS
After a repo sync on Jan 9, the following further patches are needed to
make Function FS work.

Fixes the following from Part 1 as well ...

error: tools/asuite/Android.bp:33:1: "asuite_adb_host_proto_py" depends on undefined module "adb_host_proto".
Or did you mean ["libboost_proto"]?

error: packages/modules/adb/fastdeploy/Android.bp:49:1: module "FastDeployTests" variant "android_common": cannot depend directly on java_sdk_library "android.test.runner"; try depending on "android.test.runner.stubs", "android.test.runner.stubs.system", "android.test.runner.stubs.test", or "android.test.runner.impl" instead
error: packages/modules/adb/fastdeploy/Android.bp:49:1: module "FastDeployTests" variant "android_common": cannot depend directly on java_sdk_library "android.test.base"; try depending on "android.test.base.stubs", "android.test.base.stubs.system", "android.test.base.stubs.test", or "android.test.base.impl" instead
error: packages/modules/adb/fastdeploy/Android.bp:49:1: module "FastDeployTests" variant "android_common": cannot depend directly on java_sdk_library "android.test.mock"; try depending on "android.test.mock.stubs", "android.test.mock.stubs.system", "android.test.mock.stubs.test", or "android.test.mock.impl" instead

prebuilts/clang/host/linux-x86/clang-r530567/include/c++/v1/__memory/unique_ptr.h:621:30: error: allocation of incomplete type '(anonymous namespace)::AbbProcess'

prebuilts/clang/host/linux-x86/clang-r530567/include/c++/v1/__memory/unique_ptr.h:66:19: error: invalid application of 'sizeof' to an incomplete type '(anonymous namespace)::AbbProcess'
   66 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");

packages/modules/adb/daemon/abb_service.cpp:86:12: error: use of undeclared identifier 'abbp'
   86 |     return abbp->sendCommand(command);

packages/modules/adb/sysdeps/env.cpp:54:23: error: use of undeclared identifier 'getenv'
   54 |     const char* val = getenv(var.data());

packages/modules/adb/client/auth.cpp:263:16: error: conversion function from 'std::nullptr_t' to 'std::string' (aka  'basic_string<char>') invokes a deleted function
  263 |         return nullptr;
      |                ^~~~~~~

packages/modules/adb/adb_mdns.h:53:14: error: no template named 'function' in namespace 'std'
   53 |         std::function<void(const std::string& service_name, const std::string& reg_type,
      |         ~~~~~^
packages/modules/adb/adb_mdns.cpp:98:5: error: no member named 'for_each' in namespace 'std'; did you mean 'std::ranges::for_each'?
   98 |     std::for_each(g_autoconn_allowedlist.begin(), g_autoconn_allowedlist.end(), [&](const int& i) {
      |     ^~~~~~~~~~~~~
      |     std::ranges::for_each

packages/modules/adb/client/fastdeploy.cpp:163:83: error: too few arguments to function call, expected 8, have 7
  163 |     if (!zip_file->getEntryInfo(entry, NULL, &manifest_len, NULL, NULL, NULL, NULL)) {

packages/modules/adb/adb_mdns.cpp:98:5: error: no member named 'for_each' in namespace 'std'; did you mean 'std::ranges::for_each'?
   98 |     std::for_each(g_autoconn_allowedlist.begin(), g_autoconn_allowedlist.end(), [&](const int& i) {